'use client';

import { SessionProvider } from 'next-auth/react';
import { Toaster } from 'react-hot-toast';

import TopNav from '@/components/TopNav';
import { SearchProvider } from '@/context/search';

import "./globals.css";
import "bootstrap-material-design/dist/css/bootstrap-material-design.min.css";

// export const metadata = {
//   title: "Blog App with Next 14",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <SessionProvider>
          <SearchProvider>
            <Toaster />
            <TopNav />
            {children}
          </SearchProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
