import { Toaster } from 'react-hot-toast';

import TopNav from '@/components/TopNav';

import "./globals.css";
import "bootstrap-material-design/dist/css/bootstrap-material-design.min.css";

export const metadata = {
  title: "Blog App with Next 14",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Toaster />
        <TopNav />
        {children}
      </body>
    </html>
  );
}
